Compression/Controllers/CompressionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Compression.Controllers
{
    public class CompressionController : Controller
    {
        // GET: HelloWorld
        public ActionResult StartView()
        {
            return View();
        }


        public ActionResult Welcome(string name, int numTimes = 1)
        {
            ViewBag.Message = "Hello " + name;
            ViewBag.NumTimes = numTimes;

            return View();
        }

    }
}

Compression/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Compression.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Compression/Views/Compression/Index.cshtml
<link href="~/Content/compression.css" rel="stylesheet" />
@{
    ViewBag.Title = "Kompresja";
}

<div class="form-group space compression">
    <label>Kompresja</label>
    <textarea class="form-control textarea" rows="8" placeholder="Wpisz tekst do kompresji"></textarea>
</div>
<div class="buttons">
    <button type="button" class="btn btn-primary comp">Kompresuj </button>
    <button type="button" class="btn btn-primary decomp">Dekompresuj</button>
</div>
<div class="form-group decompression">
    <label>Dekompresja</label>
    <textarea class="form-control textarea" rows="8" placeholder="Wpisz tekst do dekompresji"></textarea>
</div>

Compression/Views/Compression/StartView.cshtml
<link href="~/Content/compression.css" rel="stylesheet" />
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
@{
    ViewBag.Title = "Kompresja";
}

<div class="form-group space compression">
    <label>Kompresja</label>
    <textarea class="form-control textarea compress" rows="8" placeholder="Wpisz tekst do kompresji"></textarea>
</div>
<div class="buttons">
    <button type="button" class="btn btn-primary comp">Kompresuj </button>
    <button type="button" class="btn btn-primary decomp">Dekompresuj</button>
</div>
<div class="form-group decompression">
    <label>Dekompresja</label>
    <textarea class="form-control textarea decompress" rows="8" placeholder="Wpisz tekst do dekompresji"></textarea>
</div>



<div class="graph-cont hidden">
    <h3>Wykres kompresja</h3>
    <h5>Ilość znaków przed</h5>
    <div class="bar bar1"></div>
    <h5>Ilość znaków po</h5>
    <div class="bar bar2"></div>
    <h5>Procent kompresji</h5>
    <div class="bar bar3"></div>

</div>

Compression/Views/Compression/Welcome.cshtml
@Scripts.Render("~/Scripts/compression.js")
@{
    ViewBag.Title = "Welcome";
}

Compression/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Compression/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Compression/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Compression/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Compression APP</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Kompresja", "StartView", "Compression", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()

    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/compression.js")
    @RenderSection("scripts", required: false)
</body>
</html>